Package.swift
* Remove Amplitude dependency from Package.swift
- This one fell through the cracks when updating from beta SDK
=> fix: remove Amplitude as dependency for SPM

Sources/Experiment/ExperimentClient.swift
'
* Set the DefaultUserProvider in the client by default
=> feat: set DefaultUserProvider by default

Experiment.xcodeproj/project.pbxproj, Sources/Experiment/Backoff.swift, Sources/Experiment/ExperimentClient.swift, Sources/Experiment/ExperimentConfig.swift, Tests/ExperimentTests/ExperimentClientTests.swift
* Add automatic retries in the background if the initial fetch request fails
- same behavior as experiment-js-client SDK
=> feat: add automatic background retries to fetch

Experiment.xcodeproj/project.pbxproj, Sources/Experiment/UserDefaultsStorage.swift, Sources/Experiment/Variant.swift, Tests/ExperimentTests/UserDefaultsStorageTests.swift, Tests/ExperimentTests/VariantTests.swift
Fixes an issue where variants where not properly being loaded from user defaults.
* underlying cause is due to the codable implementation failing if the payload is nil
Added simple tests for variant encoding/decoding and storage functionality
* Does your PR have a breaking change?:   yes
=> fix: fix variant encoding/decoding from storage

Experiment.xcodeproj/project.pbxproj, Sources/Experiment/ExperimentAnalyticsEvent.swift, Sources/Experiment/ExperimentAnalyticsProvider.swift, Sources/Experiment/ExperimentClient.swift, Sources/Experiment/ExperimentConfig.swift, Sources/Experiment/ExposureEvent.swift, Tests/ExperimentTests/ExperimentClientTests.swift
* Deprecate `setUserProvider` & `getUserProvider`. Support user provider in config.
* Add analytics provider & event interface to config.
* Automatically track exposure events through analytics provider when `variant` is called. 
=> feat: exposure tracking through analytics provider

Sources/Experiment/ExperimentClient.swift
* Revert changing the fetch from POST to GET with the user info in a header
=> fix: revert post to get with user in header

Sources/Experiment/ExperimentUser.swift, Tests/ExperimentTests/ExperimentUserTests.swift
add ability to add and query non-string user properties on the experiment user object in a backwards compatible manner.
* Does your PR have a breaking change?:   No
=> feat: allow for non-string user property values

Sources/Experiment/ExperimentClient.swift, Tests/ExperimentTests/ExperimentClientTests.swift
The expected behavior of the experiment client when fetching variants for a user is that if the user passed into fetch is empty, the fetch will occur with the current user. 
=> fix: dont overwrite stored user with empty user on fetch

Sources/Experiment/Backoff.swift, Sources/Experiment/Variant.swift, Tests/ExperimentTests/VariantTests.swift
=> fix: fix variant equality for object payloads

Experiment.xcodeproj/project.pbxproj, Sources/Experiment/ExperimentClient.swift, Sources/Experiment/UserSessionExposureTracker.swift, Tests/ExperimentTests/ConnectorIntegrationTests.swift, Tests/ExperimentTests/UserSessionExposureTrackerTests.swift
Invalidate the once-per-session-per-flag exposure cache when the user id or device Id changes.
=> feat: invalidate exposure cache on user identity change

Sources/Experiment/ExperimentClient.swift
increase integration timeout to 10 seconds
=> fix: increase integration timeout to 10 seconds

Sources/Experiment/ExperimentClient.swift
Makes `clear()` method from `ExperimentClient` public so client can reset memory cache.
Related issue: https://github.com/amplitude/experiment-ios-client/issues/27
* Does your PR have a breaking change?:
=> fix: Make `clear()` method public

Sources/Experiment/ConnectorUserProvider.swift, Tests/ExperimentTests/ConnectorIntegrationTests.swift
=> fix: fix the connector user provider when id is set prior to provider init

Sources/Experiment/ExperimentClient.swift, Sources/Experiment/ExperimentConfig.swift, Tests/ExperimentTests/ExperimentClientTests.swift
call fetch on start by default
=> fix: call fetch on start by default

Sources/Experiment/Variant.swift, Tests/ExperimentTests/VariantTests.swift
Fix the translation for legacy payloads loaded from storage. fixes #39 
=> fix: fix the translation of legacy variant payloads from storage

Sources/Experiment/ExperimentClient.swift, Sources/Experiment/ExperimentConfig.swift, Tests/ExperimentTests/ExperimentClientTests.swift
=> feat: bootstrap initial local evaluation flags

AmplitudeExperiment.podspec, Experiment.xcodeproj/project.pbxproj, Package.swift, Sources/Experiment/PrivacyInfo.xcprivacy
=> fix: add privacy manifest

AmplitudeExperiment.podspec
Prevents name conflicts for statically linked libraries in Cocoapods, see: https://guides.cocoapods.org/syntax/podspec.html#resource_bundles
=> fix: Adopt resource bundle for privacy manifest in Cocoapods

.github/workflows/test.yml, Sources/Experiment/ExperimentUser.swift, Tests/ExperimentTests/ExperimentUserTests.swift
fix: toDictionary function should convert Date object to string
* Does your PR have a breaking change?:  No
=> fix: toDictionary function should convert Date object to string

Sources/Experiment/ExperimentClient.swift
Summary
Exposes `stop()` method as part of the `ExperimentClient` protocol 
https://github.com/amplitude/experiment-ios-client/issues/58
=> fix: Make `stop` method public

Sources/Experiment/ExperimentClient.swift
This PR ensures that `DefaultExperimentClient.start` will always call the provided completion block.
This fixes an issue where wrapping the method for Swift Concurrency could result in a leaked continuation.
* Does your PR have a breaking change?:  No
=> fix: ensure `completion` block is always called in `DefaultExperimentClient`

Cartfile.resolved, Sources/Experiment/ExperimentClient.swift, Sources/Experiment/ExperimentConfig.swift, Tests/ExperimentTests/ExperimentClientTests.swift
* Set the default flag polling interval to 5 min
* Add polling interval config with min value of 1 min
* Does your PR have a breaking change?:
=> feat: increase flag polling interval; add flag poller interval config

Sources/Experiment/DefaultUserProvider.swift
Update platform and device values. 
* Does your PR have a breaking change?: No.
=> feat: Update platform values

AmplitudeExperiment.podspec, Experiment.xcodeproj/project.pbxproj, Package.swift, Sources/Experiment/ExperimentClient.swift, Sources/Experiment/Variant.swift, Tests/ExperimentTests/ExperimentClientTests.swift
=> fix: add synchronization around the client's user object

Sources/Experiment/Variant.swift, Tests/ExperimentTests/VariantTests.swift
Fix but where expKey was not being properly set when the JSON object was parsed if both the expKey and metadata experiment key were already set in the raw form.
=> fix: fix variant experiment key serialization w/ both keys set

AmplitudeExperiment.podspec, Cartfile, Cartfile.resolved, Experiment.xcodeproj/project.pbxproj, Package.swift, Package@swift-5.9.swift, Sources/Experiment/ExperimentClient.swift, Sources/Experiment/ExperimentConfig.swift, Sources/Experiment/ExperimentPlugin.swift, Tests/ExperimentTests/ExperimentPluginTests.swift
Initial Unified SDK integration for Experiment
Adds `AmplitudeCore` dependency and new `ExperimentPlugin` to directly integrate with Amplitude, bypassing analytics-connector.
=> feat: add core dependency and plugin

Sources/Experiment/ExperimentPlugin.swift
Improves the plugin interface for ObjC.
=> fix: improve plugin objc interface

.github/workflows/release.yml, .github/workflows/test.yml, Package@swift-6.2.swift
- Add a Swift 6.2-specific Package.swift, in which the supported versions of iOS and watchOS are raised to 12 to avoid warnings in Xcode 26
We will also make similar changes in AmplitudeCore-Swift. Because the Experiment depends on AmplitudeCore, it’s necessary to modify it first.
Related Issue: https://github.com/amplitude/Amplitude-Swift/issues/314
- Updated and fixed the workflow configuration.
=> fix: avoid supported version deprecated warning

Package@swift-6.2.swift
This PR specifies the Swift 5 language mode in the Swift 6.2 manifest introduced by #76.
Every package manifest with swift-tools-version 6.0 or greater compiles all target in language mode v6 by default; every target that only compiles in v5, like `Experiment`, needs to actively be configured with that setting.
It resolves #77 with the following build error:
* Does your PR have a breaking change?: no
=> fix: swift 6.2 manifest compiles in swift 6 language mode

Tests/ExperimentTests/ExperimentClientTests.swift, Tests/ExperimentTests/ObjectiveCTest.m
Fix tests' assertions to only assert evaluationId to be not null. 
=> fix: tests assertion ignore evaluationId
